# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Waller' do
  
  pod 'CoreBitcoin', :podspec => 'https://raw.github.com/oleganza/CoreBitcoin/master/CoreBitcoin.podspec'

end
